name: Build and Push Docker Image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: darkdragos
          password: ${{ secrets.GITHUB_TOKEN }}
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/darkdragos/homework:latest  
          WWW-Authenticate: Basic